name: Auto Approve

on:
  pull_request:
    branches:
    - "testing"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'lucastnguyen'
      with:
        github-token: "${{ secrets.ACTION_APPROVAL }}"
