name: CI Testing

on: 
 - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        npm install jest
        npm install -g expo-cli
        npm install react-native-maps
        npm install react-native-collapsible-list
        npm install firebase
        cd app/UCSBB/
        npm run test
