name: CI Testing

on: 
 - push
 - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        cd app/UCSBB/
        npm run test
