name: CI Testing

on: 
 - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        ls
        echo 'cd to app/UCSBB/'
        cd app/UCSBB/
        ls
        npm install jest
        ls
        npm run test
